In [1]:
import numpy as np

In [2]:
x = np.array([2,4,5])
y = np.array([-1,2,5])

In [3]:
np.dot(x,y)

31

In [4]:
np.dot(5,6)

30

In [6]:
5*x

array([10, 20, 25])

In [9]:
m1 = np.array([[5,-1,0],[6,-2,1],[-5,4,2],[7,-1,2]])

In [10]:
m1

array([[ 5, -1,  0],
       [ 6, -2,  1],
       [-5,  4,  2],
       [ 7, -1,  2]])

In [11]:
m2 = np.array([[3,2],[-1,7],[-8,4]])
m2

array([[ 3,  2],
       [-1,  7],
       [-8,  4]])

In [12]:
np.dot(m1,m2)

array([[ 16,   3],
       [ 12,   2],
       [-35,  26],
       [  6,  15]])