In [1]:
import numpy as np
b = np.array([4,7,2,9],float)

In [2]:
b[3]

9.0

In [3]:
# the algorithm of elimination process requires 3 nested loops
# 3a-2b+5c = 2
# 4a+5b+8c+d = 4
# a+b+2c+d = 5
# 2a+7b+6c+5d = 7

In [4]:
from numpy import array ,zeros

In [11]:
a = array([[3,-2,5,0],
          [4,5,8,1],
          [1,1,2,1],
          [2,7,6,5]],float);

b = array([2,4,5,7],float);
n = len(b);

# x is the solution vector

x = zeros(n,float);

In [12]:
# elimination process
for k in range(n-1):
    for i in range(k+1,n):
        if a[i,k] == 0:
            continue;
        else:
            factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] - a[i,j] * factor;
        b[i] = b[k] - b[i] * factor;

In [14]:
print(a)
print(b)

[[ 3.         -2.          5.          0.        ]
 [ 0.         -5.75       -1.         -0.75      ]
 [ 0.          0.          0.15        2.7       ]
 [ 0.          0.          0.          2.21785714]]
[ 2.         -1.         13.95       13.43035714]


In [15]:
# back subtitution
x[n-1] = b[n-1]/a[n-1,n-1];
for i in range(n-2,-1,-1):
    sum = 0;
    for j in range(i+1,n):
        sum = a[i,j] * x[j];
        x[i] = (b[i] - sum)/a[i,i];
    

In [17]:
print(x)

[  0.66666667  -0.61594203 -16.           6.05555556]
