In [1]:
import numpy as np
a = np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
a.T

array([1, 2, 3])

In [4]:
# in python vectors can not be transposed

In [5]:
a.shape

(3,)

In [7]:
#but if we reshape it then we can transpose it
a_reshape = a.reshape(1,3)
a_reshape

array([[1, 2, 3]])

In [8]:
a_reshape.T

array([[1],
       [2],
       [3]])

In [9]:
x = np.array([[1,2,3],[4,5,6]])

In [10]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])