In [1]:
import numpy as np

In [2]:
s = 5
s

5

In [3]:
# vectors
v = np.array([1,-2,1])
# n dimensional array

In [4]:
v
# v is a row vetor

array([ 1, -2,  1])

In [5]:
# matrices
m = np.array([[5,12,1],
             [10,20,25]])

In [6]:
m

array([[ 5, 12,  1],
       [10, 20, 25]])

In [7]:
type(m)

numpy.ndarray

In [8]:
m.shape

(2, 3)

In [9]:
v.shape

(3,)

In [12]:
v.reshape(1,3)
# this gives us a row vector

array([[ 1, -2,  1]])

In [13]:
v.reshape(3,1)
# this gives us a column vector

array([[ 1],
       [-2],
       [ 1]])