#                                      Creating a tensor

In [1]:
# scaler is 1*1 matrix
# can be thought as a vector of length 1
# rank of scaler is 0

In [2]:
# vector is a 1*m or a m*1 matrix
# every element is a scelar

In [3]:
# matrices are a collection of vectors
# dimension of matrix is m*n
# either collection of n vectors of dimension m*1
# or collection of m vectors of dimention n*1

In [4]:
# scelar,vectors and matrices are all tensors with a rank 0,1,2
# rank 3 tensors are collection of matrices with a dimension of k*m*n

In [5]:
import numpy as np;

In [7]:
m1 = np.array([[5,2,3],
             [1,7,9]])
print(m1)

[[5 2 3]
 [1 7 9]]


In [8]:
m2 = np.array([[8,2,5],
             [1,2,9]])
print(m2)

[[8 2 5]
 [1 2 9]]


In [9]:
t = np.array([m1,m2])

In [10]:
print(t)

[[[5 2 3]
  [1 7 9]]

 [[8 2 5]
  [1 2 9]]]


In [12]:
t.shape

(2, 2, 3)

In [13]:
m1 + m2

array([[13,  4,  8],
       [ 2,  9, 18]])

In [14]:
m1 - m2

array([[-3,  0, -2],
       [ 0,  5,  0]])